### ISSUE TITLE
Collapse the comment itself

### ISSUE THREAD

**Issue by debnath-d** [jeffjadulco/hn#1]
Currently clicking on each comment only collapses the replies to the comment, not the comment itself. Is it possible to collapse the comment itself along with the replies, just like reddit?

(BTW, thanks for making this, it's great!)

**Comment by jeffjadulco** [comment]
I've been experimenting with this for days and what really worked for me (and the easiest to implement) is to just hide the parent comment itself just like what you mentioned. It is now live with the latest commit. 

I also made it so that clicking on the `xxx comments` button will toggle collapse for all the comments which, surprisingly, improved my overall reading and navigating experience.

**Comment by debnath-d** [comment]
This is lovely! Thanks a lot again!
